version: 2
multi-ecosystem-groups:
  bundler:
    schedule:
      interval: weekly
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      github_actions:
        patterns:
          - "*"
  - package-ecosystem: bundler
    directory: /
    versioning-strategy: lockfile-only
    patterns:
      - "*"
    multi-ecosystem-group: bundler
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    versioning-strategy: lockfile-only
    groups:
      npm:
        patterns:
          - "*"
  - package-ecosystem: bundler
    directory: /gemfiles/rails_72
    versioning-strategy: lockfile-only
    patterns:
      - "*"
    multi-ecosystem-group: bundler
    ignore:
      - dependency-name: rails
        versions: ">= 8.0.0"
      - dependency-name: rails-i18n
        versions: ">= 8.0.0"
      - dependency-name: railties
        versions: ">= 8.0.0"
  - package-ecosystem: bundler
    directory: /gemfiles/rails_80
    versioning-strategy: lockfile-only
    patterns:
      - "*"
    multi-ecosystem-group: bundler
    ignore:
      - dependency-name: rails
        versions: ">= 8.1.0"
      - dependency-name: rails-i18n
        versions: ">= 8.1.0"
