---

version: 2

updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
    versioning-strategy: lockfile-only

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    versioning-strategy: lockfile-only

  - package-ecosystem: bundler
    directory: /docs
    schedule:
      interval: daily
    versioning-strategy: lockfile-only

  - package-ecosystem: bundler
    directory: /gemfiles/rails_60
    schedule:
      interval: daily
    versioning-strategy: lockfile-only

  - package-ecosystem: bundler
    directory: /gemfiles/rails_61
    schedule:
      interval: daily
    versioning-strategy: lockfile-only

  - package-ecosystem: bundler
    directory: /gemfiles/rails_61_turbolinks
    schedule:
      interval: daily
    versioning-strategy: lockfile-only

  - package-ecosystem: bundler
    directory: /gemfiles/rails_61_webpacker
    schedule:
      interval: daily
    versioning-strategy: lockfile-only
