---

language: ruby

sudo: false

bundler_args: --without development

cache: bundler

before_install:
  - export PATH=$(npm bin):$PATH && if [ $(phantomjs --version) != '2.1.1' ]; then npm install phantomjs-prebuilt; fi
  - gem update --system # use the very latest Rubygems
  - rvm @global do gem uninstall bundler -a -x
  - rvm @global do gem install bundler -v 1.14.3 # latest version known to work

before_script:
  - bundle exec rake setup

script:
  - bundle exec rake test

rvm:
  - jruby-9.1.7.0
  - 1.9.3
  - 2.2.6
  - 2.3.3
  - 2.4.0

gemfile:
  - gemfiles/rails_32.gemfile
  - gemfiles/rails_40.gemfile
  - gemfiles/rails_41.gemfile
  - gemfiles/rails_42.gemfile
  - gemfiles/rails_50.gemfile

env:
  global:
    - JRUBY_OPTS="-J-Xmx1024m --debug"

matrix:
  fast_finish: true

  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/rails_50.gemfile

    - rvm: 2.4.0
      gemfile: gemfiles/rails_32.gemfile

    - rvm: 2.4.0
      gemfile: gemfiles/rails_40.gemfile

    - rvm: 2.4.0
      gemfile: gemfiles/rails_41.gemfile

  allow_failures:
    - rvm: jruby-9.1.7.0
      gemfile: gemfiles/rails_50.gemfile

    - rvm: 2.4.0
      gemfile: gemfiles/rails_42.gemfile

notifications:
  irc:
    channels:
      - irc.freenode.org#activeadmin

    on_success: change
    on_failure: always
    skip_join: true

    template:
      - "(%{branch}/%{commit} by %{author}): %{message} (%{build_url})"
