---

addons:
  chrome: stable

language: ruby

sudo: false

dist: trusty

bundler_args: --without development

cache: bundler

before_script:
  - unset _JAVA_OPTIONS

before_install:
  - gem update --system # use the very latest Rubygems
  - gem install bundler # use the very latest Bundler

script:
  - bundle exec rake
  - bundle exec rake docs:build
  - bundle exec rake lint

rvm:
  - jruby-9.2.0.0
  - 2.3.7
  - 2.4.4
  - 2.5.1

gemfile:
  - gemfiles/rails_42.gemfile
  - gemfiles/rails_50.gemfile
  - gemfiles/rails_51.gemfile
  - gemfiles/rails_52.gemfile

env:
  global:
    - JRUBY_OPTS="-J-Xmx1024m --dev --debug"
    - COVERAGE=true

matrix:
  fast_finish: true

  allow_failures:
    - rvm: jruby-9.2.0.0
