language: ruby
sudo: false
install:
  - ./script/travis_cache download_bundle
  - gem install bundler # use the very latest Bundler
  - bundle install --without development --path=./bundle
  - bundle clean # delete now-outdated gems
  - ./script/travis_cache download_app
  - bundle exec rake setup
  - ./script/travis_cache upload
script:
  - bundle exec rake test
rvm:
  - 1.9
  - 2.3.0
  - jruby-9.0.5.0
env:
  matrix:
    - RAILS=3.2.22
    - RAILS=4.2.5
    - RAILS=5.0.0
  global:
    - JRUBY_OPTS="-J-Xmx1024m --debug"
matrix:
  fast_finish: true
  exclude:
    - rvm: 1.9
      env: RAILS=5.0.0
  allow_failures:
    - rvm: jruby-9.0.5.0
      env: RAILS=5.0.0
notifications:
  irc:
    channels:
      - irc.freenode.org#activeadmin
    on_success: change
    on_failure: always
    skip_join: true
    template:
      - "(%{branch}/%{commit} by %{author}): %{message} (%{build_url})"
