language: ruby
script: bundle exec rake test
rvm:
  - 1.9.3
  - 2.0.0
gemfile:
  - gemfiles/rails_3_2.gemfile
  - gemfiles/rails_4_0.gemfile
matrix:
  allow_failures:
    - gemfile: gemfiles/rails_4_0.gemfile
