language: ruby
script: bundle exec rake test_with_coveralls
rvm:
  - 1.9.3
  - 2.1.0
env:
  - RAILS=3.2.16
  - RAILS=4.0.2
notifications:
  irc:
    channels:
      - "irc.freenode.org#activeadmin"
    on_success: change
    on_failure: always
    skip_join: true
    template:
      - "(%{branch}/%{commit} by %{author}): %{message} (%{build_url})"
