---

version: 2.1

.install_rubygems: &install_rubygems
  run:
    name: Install a specific rubygems version
    command: gem update --system 3.1.4

.install_bundler: &install_bundler
  run:
    name: Install a specific bundler version
    command: gem install bundler -v 2.2.0.rc.1

.install_build_deps: &install_build_deps
  run:
    name: Install build dependencies so that sassc-rails extension builds
    command: sudo apt install make gcc g++

.copy_current_gemfile: &copy_current_gemfile
  run:
    name: Cat current Gemfile to a specific file so caching works
    command: cat "$BUNDLE_GEMFILE.lock" > current_gemfile.lock

.restore_gems: &restore_gems
  restore_cache:
    keys:
      - bundler-dependencies-{{ checksum "current_gemfile.lock" }}-{{ .Environment.CIRCLE_JOB }}

.install_dependencies: &install_dependencies
  run:
    name: Install dependencies
    command: |
      bundle config set --local path /root/project/vendor/bundle
      bundle install --jobs 3

.save_gems: &save_gems
  save_cache:
    key: bundler-dependencies-{{ checksum "current_gemfile.lock" }}-{{ .Environment.CIRCLE_JOB }}
    paths:
      - vendor/bundle

.create_test_app: &create_test_app
  run:
    name: Create test app
    command: COVERAGE=true PARALLEL_TEST_PROCESSORS=4 bin/rake setup

.restore_test_reporter: &restore_test_reporter
  attach_workspace:
    at: bin

.restore_coverage: &restore_coverage
  attach_workspace:
    at: coverage

.format_coverage: &format_coverage
  run:
    name: Format coverage
    command: |
      bin/prepare_coverage
      bin/test-reporter format-coverage --output coverage/codeclimate.$CIRCLE_JOB.json

.save_coverage: &save_coverage
  persist_to_workspace:
      root: coverage
      paths:
        - codeclimate.*.json

.submit_coverage: &submit_coverage
  run:
    name: Upload coverage results to Code Climate
    command: |
      bin/test-reporter sum-coverage coverage/codeclimate.*.json
      bin/test-reporter upload-coverage

.save_test_app: &save_test_app
  persist_to_workspace:
    root: tmp/test_apps
    paths:
      - rails_*

.restore_test_app_from_workspace: &restore_test_app_from_workspace
  attach_workspace:
    at: tmp/test_apps

.restore_test_times: &restore_test_times
  restore_cache:
    keys:
      - testtime-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}
      - testtime-master-{{ .Environment.CIRCLE_JOB }}

.run_tests: &run_tests
  run:
    name: Run RSpec tests
    command: |
      COVERAGE=true PARALLEL_TEST_PROCESSORS=4 PARALLEL_TEST_HEARTBEAT_INTERVAL=3600 bin/parallel_rspec spec/
      COVERAGE=true RSPEC_FILESYSTEM_CHANGES=true bin/rspec

.run_features: &run_features
  run:
    name: Run Cucumber features
    command: |
      COVERAGE=true PARALLEL_TEST_PROCESSORS=4 PARALLEL_TEST_HEARTBEAT_INTERVAL=3600 bin/parallel_cucumber features/
      COVERAGE=true bin/cucumber --profile filesystem-changes
      COVERAGE=true bin/cucumber --profile class-reloading

.save_test_times: &save_test_times
  save_cache:
    key: testtime-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}
    paths:
      - tmp/parallel_runtime_rspec.log
      - tmp/parallel_runtime_cucumber.log

.generate_docs: &generate_docs
  run:
    name: Generate docs
    command: bin/rake docs:build

.run_lints: &run_lints
  run:
    name: Run lints
    command: COVERAGE=true bin/rake lint

.run_bug_report_template: &run_bug_report_template
  run:
    name: Run bug report template
    command: ACTIVE_ADMIN_PATH=. ruby tasks/bug_report_template.rb

.test_steps: &test_steps
  - checkout
  - *install_rubygems
  - *install_bundler
  - *install_build_deps
  - *copy_current_gemfile
  - *restore_gems
  - *install_dependencies
  - *save_gems
  - *restore_test_app_from_workspace
  - *restore_test_times
  - *restore_test_reporter
  - *run_tests
  - *run_features
  - *format_coverage
  - *save_coverage
  - *save_test_times

.test_app_steps: &test_app_steps
  - checkout
  - *install_rubygems
  - *install_bundler
  - *copy_current_gemfile
  - *restore_gems
  - *install_dependencies
  - *restore_test_reporter
  - *save_gems
  - *create_test_app
  - *format_coverage
  - *save_coverage
  - *save_test_app

jobs:
  setup_coverage:
    docker:
      - image: circleci/ruby:2.7.1

    steps:
      - run:
          name: Download Code Climate test-reporter
          command: |
            mkdir bin
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-0.8.0-linux-amd64 > bin/test-reporter
            chmod +x  bin/test-reporter

      - persist_to_workspace:
          root: bin
          paths:
            - test-reporter

  upload_coverage:
    docker:
      - image: circleci/ruby:2.7.1
        environment:
          CC_TEST_REPORTER_ID: 8d5fcf7abea6d56c625104a9d1a81140a588a7f546f4fa9de9bc6ffc8feaaf70

    steps:
      - *restore_test_reporter
      - *restore_coverage
      - *submit_coverage

  testapp52:
    docker:
      - image: circleci/ruby:2.7.1-node
        user: root

    environment:
      BUNDLE_GEMFILE: gemfiles/rails_52/Gemfile

    steps:
      *test_app_steps

  testapp60:
    docker:
      - image: circleci/ruby:2.7.1-node
        user: root

    environment:
      BUNDLE_GEMFILE: Gemfile

    steps:
      *test_app_steps

  testapp60turbolinks:
    docker:
      - image: circleci/ruby:2.7.1-node
        user: root

    environment:
      BUNDLE_GEMFILE: gemfiles/rails_60_turbolinks/Gemfile

    steps:
      *test_app_steps

  testapp60webpacker:
    docker:
      - image: circleci/ruby:2.7.1-node
        user: root

    environment:
      BUNDLE_GEMFILE: gemfiles/rails_60_webpacker/Gemfile

    steps:
      *test_app_steps

  lint_and_docs:
    docker:
      - image: circleci/ruby:2.7.1-node
        user: root

    environment:
      BUNDLE_GEMFILE: Gemfile

    steps:
      - checkout
      - *install_rubygems
      - *install_bundler
      - *copy_current_gemfile
      - *restore_gems
      - *install_dependencies
      - *save_gems
      - *generate_docs
      - *restore_test_reporter
      - *run_lints
      - *run_bug_report_template
      - *format_coverage
      - *save_coverage

  ruby25rails52:
    docker:
      - image: circleci/ruby:2.5.8-node-browsers@sha256:772449521f5bdc456b3da1226d4070c46b53868a7b7b41f4de2318f1358c8fe6
        user: root

    environment:
      BUNDLE_GEMFILE: gemfiles/rails_52/Gemfile

    steps:
      *test_steps

  ruby25rails60:
    docker:
      - image: circleci/ruby:2.5.8-node-browsers@sha256:772449521f5bdc456b3da1226d4070c46b53868a7b7b41f4de2318f1358c8fe6
        user: root

    environment:
      BUNDLE_GEMFILE: Gemfile

    steps:
      *test_steps

  ruby26rails52:
    docker:
      - image: circleci/ruby:2.6.6-node-browsers@sha256:6fecbb049a4a8a561566a0dd976a617443d14346a17e6d12d83db882684273e1
        user: root

    environment:
      BUNDLE_GEMFILE: gemfiles/rails_52/Gemfile

    steps:
      *test_steps

  ruby26rails60:
    docker:
      - image: circleci/ruby:2.6.6-node-browsers@sha256:6fecbb049a4a8a561566a0dd976a617443d14346a17e6d12d83db882684273e1
        user: root

    environment:
      BUNDLE_GEMFILE: Gemfile

    steps:
      *test_steps

  ruby26rails60turbolinks:
    docker:
      - image: circleci/ruby:2.6.6-node-browsers@sha256:6fecbb049a4a8a561566a0dd976a617443d14346a17e6d12d83db882684273e1
        user: root

    environment:
      BUNDLE_GEMFILE: gemfiles/rails_60_turbolinks/Gemfile

    steps:
      *test_steps

  ruby26rails60webpacker:
    docker:
      - image: circleci/ruby:2.6.6-node-browsers@sha256:6fecbb049a4a8a561566a0dd976a617443d14346a17e6d12d83db882684273e1
        user: root

    environment:
      BUNDLE_GEMFILE: gemfiles/rails_60_webpacker/Gemfile

    steps:
      *test_steps

  ruby27rails52:
    docker:
      - image: circleci/ruby:2.7.1-node-browsers@sha256:94789a1524fa16521f6397f05ff9d4569c102ae4479135ee3f78e3b4d25c1b0e
        user: root

    environment:
      BUNDLE_GEMFILE: gemfiles/rails_52/Gemfile

    steps:
      *test_steps

  ruby27rails60:
    docker:
      - image: circleci/ruby:2.7.1-node-browsers@sha256:94789a1524fa16521f6397f05ff9d4569c102ae4479135ee3f78e3b4d25c1b0e
        user: root

    environment:
      BUNDLE_GEMFILE: Gemfile

    steps:
      *test_steps

  ruby27rails60turbolinks:
    docker:
      - image: circleci/ruby:2.7.1-node-browsers@sha256:94789a1524fa16521f6397f05ff9d4569c102ae4479135ee3f78e3b4d25c1b0e
        user: root

    environment:
      BUNDLE_GEMFILE: gemfiles/rails_60_turbolinks/Gemfile

    steps:
      *test_steps

  ruby27rails60webpacker:
    docker:
      - image: circleci/ruby:2.7.1-node-browsers@sha256:94789a1524fa16521f6397f05ff9d4569c102ae4479135ee3f78e3b4d25c1b0e
        user: root

    environment:
      BUNDLE_GEMFILE: gemfiles/rails_60_webpacker/Gemfile

    steps:
      *test_steps

  jruby92rails52:
    docker:
      - image: circleci/jruby:9.2.13.0-node-browsers@sha256:7c1a2e5d083dbcbfd29c48ebaff1cbd6812824747570746577566dcf4685bb02
        user: root

    environment:
      BUNDLE_GEMFILE: gemfiles/rails_52/Gemfile
      JRUBY_OPTS: -J-Xmx1024m --dev --debug

    steps:
      *test_steps

  jruby92rails60:
    docker:
      - image: circleci/jruby:9.2.13.0-node-browsers@sha256:7c1a2e5d083dbcbfd29c48ebaff1cbd6812824747570746577566dcf4685bb02
        user: root

    environment:
      BUNDLE_GEMFILE: Gemfile
      JRUBY_OPTS: -J-Xmx1024m --dev --debug

    steps:
      *test_steps

workflows:
  version: 2

  #
  # The workflow has three types of jobs:
  #
  # * A lint job to run style checks.
  # * Jobs that create test apps for each supported rails version.
  # * Jobs that run tests, one for each supported [ruby_version, rails_version]
  #   combination. Every test job for a specific rails version reuses the test
  #   app created for that specific rails version.
  #
  build:
    jobs:
      - setup_coverage

      - lint_and_docs:
          requires:
            - setup_coverage

      - testapp52:
          requires:
            - setup_coverage

      - testapp60:
          requires:
            - setup_coverage

      - testapp60turbolinks:
          requires:
            - setup_coverage

      - testapp60webpacker:
          requires:
            - setup_coverage

      - ruby25rails52:
          requires:
            - testapp52

      - ruby25rails60:
          requires:
            - testapp60

      - ruby26rails52:
          requires:
            - testapp52

      - ruby26rails60:
          requires:
            - testapp60

      - ruby26rails60turbolinks:
          requires:
            - testapp60turbolinks

      - ruby26rails60webpacker:
          requires:
            - testapp60webpacker

      - ruby27rails52:
          requires:
            - testapp52

      - ruby27rails60:
          requires:
            - testapp60

      - ruby27rails60turbolinks:
          requires:
            - testapp60turbolinks

      - ruby27rails60webpacker:
          requires:
            - testapp60webpacker

      - jruby92rails52:
          requires:
            - testapp52

      - jruby92rails60:
          requires:
            - testapp60

      - upload_coverage:
          requires:
            - lint_and_docs

            - testapp52
            - testapp60
            - testapp60turbolinks
            - testapp60webpacker

            - ruby25rails52
            - ruby25rails60

            - ruby26rails52
            - ruby26rails60
            - ruby26rails60turbolinks
            - ruby26rails60webpacker

            - ruby27rails52
            - ruby27rails60
            - ruby27rails60turbolinks
            - ruby27rails60webpacker

            - jruby92rails52
            - jruby92rails60
