---

version: 2.1

steps: &steps
  - checkout

  - run:
      name: Install a specific bundler version
      command: gem install bundler -v 1.16.6

  - run:
      name: Cat current Gemfile to a specific file so caching works
      command: cat "$BUNDLE_GEMFILE.lock" > current_gemfile.lock

  - restore_cache:
      keys:
        - bundler-dependencies-{{ checksum "current_gemfile.lock" }}

  - run:
      name: Install dependencies
      command: bundle install --without development --path vendor/bundle --retry 3 --jobs 3

  - run:
      name: Install chromedriver
      command: bin/install_chromedriver.sh

  - save_cache:
      key: bundler-dependencies-{{ checksum "current_gemfile.lock" }}
      paths:
        - vendor/bundle

  - run:
      name: Run checks
      command: |
        COVERAGE=true bundle exec rake
        bundle exec rake docs:build
        bundle exec rake lint

jobs:
  ruby23rails42:
    docker:
      - image: circleci/ruby:2.3.7-node-browsers

    environment:
      BUNDLE_GEMFILE: gemfiles/rails_42.gemfile

    steps:
      *steps

  ruby23rails50:
    docker:
      - image: circleci/ruby:2.3.7-node-browsers

    environment:
      BUNDLE_GEMFILE: gemfiles/rails_50.gemfile

    steps:
      *steps

  ruby23rails51:
    docker:
      - image: circleci/ruby:2.3.7-node-browsers

    environment:
      BUNDLE_GEMFILE: gemfiles/rails_51.gemfile

    steps:
      *steps

  ruby23rails52:
    docker:
      - image: circleci/ruby:2.3.7-node-browsers

    environment:
      BUNDLE_GEMFILE: Gemfile

    steps:
      *steps

  ruby24rails42:
    docker:
      - image: circleci/ruby:2.4.4-node-browsers

    environment:
      BUNDLE_GEMFILE: gemfiles/rails_42.gemfile

    steps:
      *steps

  ruby24rails50:
    docker:
      - image: circleci/ruby:2.4.4-node-browsers

    environment:
      BUNDLE_GEMFILE: gemfiles/rails_50.gemfile

    steps:
      *steps

  ruby24rails51:
    docker:
      - image: circleci/ruby:2.4.4-node-browsers

    environment:
      BUNDLE_GEMFILE: gemfiles/rails_51.gemfile

    steps:
      *steps

  ruby24rails52:
    docker:
      - image: circleci/ruby:2.4.4-node-browsers

    environment:
      BUNDLE_GEMFILE: Gemfile

    steps:
      *steps

  ruby25rails42:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers

    environment:
      BUNDLE_GEMFILE: gemfiles/rails_42.gemfile

    steps:
      *steps

  ruby25rails50:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers

    environment:
      BUNDLE_GEMFILE: gemfiles/rails_50.gemfile

    steps:
      *steps

  ruby25rails51:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers

    environment:
      BUNDLE_GEMFILE: gemfiles/rails_51.gemfile

    steps:
      *steps

  ruby25rails52:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers

    environment:
      BUNDLE_GEMFILE: Gemfile

    steps:
      *steps

  jruby91rails50:
    docker:
      - image: ccistaging/jruby:9.1.17.0-node-browsers

    environment:
      BUNDLE_GEMFILE: gemfiles/rails_50.gemfile
      JRUBY_OPTS: -J-Xmx1024m --dev --debug

    steps:
      *steps

  jruby91rails51:
    docker:
      - image: ccistaging/jruby:9.1.17.0-node-browsers

    environment:
      BUNDLE_GEMFILE: gemfiles/rails_51.gemfile
      JRUBY_OPTS: -J-Xmx1024m --dev --debug

    steps:
      *steps

  jruby91rails52:
    docker:
      - image: ccistaging/jruby:9.1.17.0-node-browsers

    environment:
      BUNDLE_GEMFILE: Gemfile
      JRUBY_OPTS: -J-Xmx1024m --dev --debug

    steps:
      *steps

  jruby92rails50:
    docker:
      - image: ccistaging/jruby:9.2.0.0-node-browsers

    environment:
      BUNDLE_GEMFILE: gemfiles/rails_50.gemfile
      JRUBY_OPTS: -J-Xmx1024m --dev --debug

    steps:
      *steps

  jruby92rails51:
    docker:
      - image: ccistaging/jruby:9.2.0.0-node-browsers

    environment:
      BUNDLE_GEMFILE: gemfiles/rails_51.gemfile
      JRUBY_OPTS: -J-Xmx1024m --dev --debug

    steps:
      *steps

  jruby92rails52:
    docker:
      - image: ccistaging/jruby:9.2.0.0-node-browsers

    environment:
      BUNDLE_GEMFILE: Gemfile
      JRUBY_OPTS: -J-Xmx1024m --dev --debug

    steps:
      *steps

workflows:
  version: 2

  build:
    jobs:
      - ruby23rails42
      - ruby23rails50
      - ruby23rails51
      - ruby23rails52

      - ruby24rails42
      - ruby24rails50
      - ruby24rails51
      - ruby24rails52

      - ruby25rails42
      - ruby25rails50
      - ruby25rails51
      - ruby25rails52

      - jruby91rails50
      - jruby91rails51
      - jruby91rails52

      - jruby92rails50
      - jruby92rails51
      - jruby92rails52
