---

version: 2.1

.install_bundler: &install_bundler
  run:
    name: Install a specific bundler version
    command: gem install bundler -v 1.16.6

.copy_current_gemfile: &copy_current_gemfile
  run:
    name: Cat current Gemfile to a specific file so caching works
    command: cat "$BUNDLE_GEMFILE.lock" > current_gemfile.lock

.restore_cache: &restore_cache
  restore_cache:
    keys:
      - bundler-dependencies-{{ checksum "current_gemfile.lock" }}-{{ .Environment.CIRCLE_JOB }}

.install_dependencies: &install_dependencies
  run:
    name: Install dependencies
    command: bundle install --without development --path /home/circleci/project/vendor/bundle --retry 3 --jobs 3

.install_chromedriver: &install_chromedriver
  run:
    name: Install chromedriver
    command: bin/install_chromedriver.sh

.save_cache: &save_cache
  save_cache:
    key: bundler-dependencies-{{ checksum "current_gemfile.lock" }}-{{ .Environment.CIRCLE_JOB }}
    paths:
      - vendor/bundle

.run_tests: &run_tests
  run:
    name: Run tests
    command: COVERAGE=true bundle exec rake

.generate_docs: &generate_docs
  run:
    name: Generate docs
    command: bundle exec rake docs:build

.run_lints: &run_lints
  run:
    name: Run lints
    command: bundle exec rake lint

.test_steps: &test_steps
  - checkout
  - *install_bundler
  - *copy_current_gemfile
  - *restore_cache
  - *install_dependencies
  - *install_chromedriver
  - *save_cache
  - *run_tests

jobs:
  lint_and_docs:
    docker:
      - image: circleci/ruby:2.5.3

    environment:
      BUNDLE_GEMFILE: Gemfile

    steps:
      - checkout
      - *install_bundler
      - *copy_current_gemfile
      - *restore_cache
      - *install_dependencies
      - *save_cache
      - *generate_docs
      - *run_lints

  ruby23rails42:
    docker:
      - image: circleci/ruby:2.3.7-node-browsers

    environment:
      BUNDLE_GEMFILE: gemfiles/rails_42.gemfile

    steps:
      *test_steps

  ruby23rails50:
    docker:
      - image: circleci/ruby:2.3.8-node-browsers

    environment:
      BUNDLE_GEMFILE: gemfiles/rails_50.gemfile

    steps:
      *test_steps

  ruby23rails51:
    docker:
      - image: circleci/ruby:2.3.8-node-browsers

    environment:
      BUNDLE_GEMFILE: gemfiles/rails_51.gemfile

    steps:
      *test_steps

  ruby23rails52:
    docker:
      - image: circleci/ruby:2.3.8-node-browsers

    environment:
      BUNDLE_GEMFILE: Gemfile

    steps:
      *test_steps

  ruby24rails42:
    docker:
      - image: circleci/ruby:2.4.4-node-browsers

    environment:
      BUNDLE_GEMFILE: gemfiles/rails_42.gemfile

    steps:
      *test_steps

  ruby24rails50:
    docker:
      - image: circleci/ruby:2.4.5-node-browsers

    environment:
      BUNDLE_GEMFILE: gemfiles/rails_50.gemfile

    steps:
      *test_steps

  ruby24rails51:
    docker:
      - image: circleci/ruby:2.4.5-node-browsers

    environment:
      BUNDLE_GEMFILE: gemfiles/rails_51.gemfile

    steps:
      *test_steps

  ruby24rails52:
    docker:
      - image: circleci/ruby:2.4.5-node-browsers

    environment:
      BUNDLE_GEMFILE: Gemfile

    steps:
      *test_steps

  ruby25rails42:
    docker:
      - image: circleci/ruby:2.5.3-node-browsers

    environment:
      BUNDLE_GEMFILE: gemfiles/rails_42.gemfile

    steps:
      *test_steps

  ruby25rails50:
    docker:
      - image: circleci/ruby:2.5.3-node-browsers

    environment:
      BUNDLE_GEMFILE: gemfiles/rails_50.gemfile

    steps:
      *test_steps

  ruby25rails51:
    docker:
      - image: circleci/ruby:2.5.3-node-browsers

    environment:
      BUNDLE_GEMFILE: gemfiles/rails_51.gemfile

    steps:
      *test_steps

  ruby25rails52:
    docker:
      - image: circleci/ruby:2.5.3-node-browsers

    environment:
      BUNDLE_GEMFILE: Gemfile

    steps:
      *test_steps

  jruby91rails50:
    docker:
      - image: ccistaging/jruby:9.1.17.0-node-browsers

    environment:
      BUNDLE_GEMFILE: gemfiles/rails_50.gemfile
      JRUBY_OPTS: -J-Xmx1024m --dev --debug

    steps:
      *test_steps

  jruby91rails51:
    docker:
      - image: ccistaging/jruby:9.1.17.0-node-browsers

    environment:
      BUNDLE_GEMFILE: gemfiles/rails_51.gemfile
      JRUBY_OPTS: -J-Xmx1024m --dev --debug

    steps:
      *test_steps

  jruby91rails52:
    docker:
      - image: ccistaging/jruby:9.1.17.0-node-browsers

    environment:
      BUNDLE_GEMFILE: Gemfile
      JRUBY_OPTS: -J-Xmx1024m --dev --debug

    steps:
      *test_steps

  jruby92rails50:
    docker:
      - image: ccistaging/jruby:9.2.0.0-node-browsers

    environment:
      BUNDLE_GEMFILE: gemfiles/rails_50.gemfile
      JRUBY_OPTS: -J-Xmx1024m --dev --debug

    steps:
      *test_steps

  jruby92rails51:
    docker:
      - image: ccistaging/jruby:9.2.0.0-node-browsers

    environment:
      BUNDLE_GEMFILE: gemfiles/rails_51.gemfile
      JRUBY_OPTS: -J-Xmx1024m --dev --debug

    steps:
      *test_steps

  jruby92rails52:
    docker:
      - image: ccistaging/jruby:9.2.0.0-node-browsers

    environment:
      BUNDLE_GEMFILE: Gemfile
      JRUBY_OPTS: -J-Xmx1024m --dev --debug

    steps:
      *test_steps

workflows:
  version: 2

  build:
    jobs:
      - lint_and_docs

      - ruby23rails42
      - ruby23rails50
      - ruby23rails51
      - ruby23rails52

      - ruby24rails42
      - ruby24rails50
      - ruby24rails51
      - ruby24rails52

      - ruby25rails42
      - ruby25rails50
      - ruby25rails51
      - ruby25rails52

      - jruby91rails50
      - jruby91rails51
      - jruby91rails52

      - jruby92rails50
      - jruby92rails51
      - jruby92rails52
