name: Bug Reports

on:
  schedule:
    # Run every day at noon UTC
    - cron: '0 12 * * *'
  pull_request:

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  RUBY_VERSION: ruby-3.3

jobs:
  bug_report_template_test:
    name: Run bug report template
    # Don't run scheduled workflow on forks
    if: ${{ github.event_name == 'pull_request' || github.repository_owner == 'activeadmin' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: tj-actions/changed-files@v45
        id: changed-files
        with:
          files: |
            app/**
            config/**
            lib/*.rb
            lib/active_admin/**
            tasks/bug_report_template.rb
            Gemfile*
            *.gemspec
      - uses: ruby/setup-ruby@v1
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - name: Run bug report template
        if: steps.changed-files.outputs.any_changed == 'true'
        run: ACTIVE_ADMIN_PATH=. ruby tasks/bug_report_template.rb
