name: GitHub Actions Lint

on:
  pull_request:

jobs:
  github_actions_lint:
    name: Run actionlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: tj-actions/changed-files@v45
        id: changed-files
        with:
          files: |
            .github/workflows/*.yaml
            .github/workflows/*.yml
      - uses: reviewdog/action-actionlint@v1
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          fail_on_error: true
          filter_mode: nofilter # added (default), diff_context, file, nofilter
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
